'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceWhatsAppCloudApi
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceWhatsAppCloudApi.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendTemplateMessage", ReplyAction:="http://tempuri.org/IService1/SendTemplateMessageResponse")>  _
        Function SendTemplateMessage(ByVal phoneNumber As String, ByVal token As String, ByVal templateId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendTemplateBillingMessage", ReplyAction:="http://tempuri.org/IService1/SendTemplateBillingMessageResponse")>  _
        Function SendTemplateBillingMessage(ByVal phoneNumber As String, ByVal customerName As String, ByVal fileNamePdf As String, ByVal fileNameXml As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/VerifyWebhook", ReplyAction:="http://tempuri.org/IService1/VerifyWebhookResponse")>  _
        Function VerifyWebhook(ByVal hub_mode As String, ByVal hub_verify_token As String, ByVal hub_challenge As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ReceiveNotification", ReplyAction:="http://tempuri.org/IService1/ReceiveNotificationResponse")>  _
        Function ReceiveNotification(ByVal payload As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceWhatsAppCloudApi.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceWhatsAppCloudApi.IService1)
        Implements ServiceWhatsAppCloudApi.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendTemplateMessage(ByVal phoneNumber As String, ByVal token As String, ByVal templateId As String) As String Implements ServiceWhatsAppCloudApi.IService1.SendTemplateMessage
            Return MyBase.Channel.SendTemplateMessage(phoneNumber, token, templateId)
        End Function
        
        Public Function SendTemplateBillingMessage(ByVal phoneNumber As String, ByVal customerName As String, ByVal fileNamePdf As String, ByVal fileNameXml As String) As String Implements ServiceWhatsAppCloudApi.IService1.SendTemplateBillingMessage
            Return MyBase.Channel.SendTemplateBillingMessage(phoneNumber, customerName, fileNamePdf, fileNameXml)
        End Function
        
        Public Function VerifyWebhook(ByVal hub_mode As String, ByVal hub_verify_token As String, ByVal hub_challenge As String) As System.IO.Stream Implements ServiceWhatsAppCloudApi.IService1.VerifyWebhook
            Return MyBase.Channel.VerifyWebhook(hub_mode, hub_verify_token, hub_challenge)
        End Function
        
        Public Function ReceiveNotification(ByVal payload As String) As String Implements ServiceWhatsAppCloudApi.IService1.ReceiveNotification
            Return MyBase.Channel.ReceiveNotification(payload)
        End Function
    End Class
End Namespace
